# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='dayDurationText',
            field=models.TextField(),
        ),
    ]
