# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20170816_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='dayDuration',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='dayDurationText',
        ),
        migrations.AddField(
            model_name='plan',
            name='isYearlyPlan',
            field=models.BooleanField(default=False),
        ),
    ]
