# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20170816_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='isYearlyPlan',
            new_name='y',
        ),
    ]
