# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_auto_20170816_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='isYearly',
            field=models.TextField(default='False'),
        ),
    ]
